language: C

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: CMAKEOPTIONS="-D OpenCL_LOCAL_HEADERS=2.0 -D OpenCL_USE_LOCAL_HEADERS=1 -D OpenCL_LIBRARY=/usr/lib/x86_64-linux-gnu/libOpenCL.so.1"
    - os: osx
      osx_image: xcode8.2
      env: CMAKEOPTIONS="-D OpenCL_USE_LOCAL_HEADERS=0"

before_install:
  - bash .travis/install_deps.sh

script:
  - mkdir build
  - pushd build
  - cmake -G"Unix Makefiles" -D CMAKE_BUILD_TYPE=Debug -D TESTS_USE_OPENCL_STUB=0 ${CMAKEOPTIONS} ..
  - make
  - ./src/utils/ccl_devinfo
  - ./tests/test_all.sh
  - make clean
  - cmake -G"Unix Makefiles" -D CMAKE_BUILD_TYPE=Debug -D TESTS_USE_OPENCL_STUB=1 ${CMAKEOPTIONS} ..
  - make tests
  - gtester ./tests/lib/test_*
  - popd
